version: "3.9"

# db(MySQL),app(Flask),web(Nginx)のコンテナを作成
services:
  db:
    container_name: MySQL
    build:
      context: .
      dockerfile: Docker/MySQL/Dockerfile
    platform: linux/x86_64
    volumes:
      - mysql_data:/var/lib/mysql
    # コンテナ内の環境変数を.env.prodを使って設定
    env_file:
      - .env.prod
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

  app:
    container_name: Flask
    build:
      context: .
      dockerfile: Docker/Flask/Dockerfile
    volumes:
      - ./app_dir:/code
      - ./static:/static
    # 8000番ポートをNginx側が接続できるよう開く
    expose:
      - "5000"
    # gunicornを起動させる
    command:  bash -c "python manage.py collectstatic --noinput && \
              gunicorn flaskpj.wsgi:application --bind 0.0.0.0:8000"
    # コンテナ内の環境変数を.env.prodを使って設定
    env_file:
      - .env.prod
    depends_on:
      db:
        # dbのヘルスチェックが終わってからappを起動させる
        condition: service_healthy

  web:
    # コンテナ名をwebに指定
    container_name: Nginx
    # NginxのDockerfileをビルドする
    build:
      # ビルドコンテキストはカレントディレクトリ
      context: .
      dockerfile: Docker/Nginx/Dockerfile
    # ボリュームを指定
    # ローカルの/staticをコンテナの/staticにマウントする
    volumes:
      - ./static:/static
    # ローカルの80番ボートをコンテナの80番ポートとつなぐ
    ports:
      - "80:80"
    # 先にappを起動してからwebを起動する
    depends_on:
      - app

volumes:
  mysql_data:
  static: